config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # List all tasks
  get 'tasks', to: 'tasks#index'

  # create a new task
  get 'tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'

  # edit a task
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch 'tasks/:id', to: 'tasks#update'

  # Show the information of one specific task
  get 'tasks/:id', to: 'tasks#show', as: :task

  #delete a task
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
    @task.title
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_task_form.html.erb
<%= form_for(task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit task</h1>
<%= render "task_form", task: @task %>
<%= link_to "Back to tasks list", tasks_path %>

app/views/tasks/index.html.erb
<h1>Your tasks</h1>

<% @tasks.each do |task| %>
  <ul>
    <li>
      <input type="checkbox" id="scales" name="scales" checked="<% task.completed %>">
      <%= link_to task.title, task_path(task) %>
      <%= link_to "Edit", edit_task_path(task) %>
      <%= link_to "🗑️",
            task_path(task),
            method: :delete,
            data: { confirm: "Are you sure?" } %>
    </li>
  </ul>
<% end %>

<%= link_to "Add a new task", tasks_new_path %>

app/views/tasks/new.html.erb
<h1>Create a new task</h1>
<%= render "task_form", task: @task %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<p><%= @task.details %></p>
<%= link_to "Back to tasks list", tasks_path %>